name: Go Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...
